// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:30ab1e84-8ab7-47b3-9aa9-d7b177f6c2b5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rftqJvfPy",
    "aws_user_pools_web_client_id": "43aj887ji0naktucn5d01ji3b8"
};


export default awsmobile;
